<a href="https://colab.research.google.com/github/WisudantyoWahyu/SISTEM-CERDAS/blob/main/classify_site_class_revenue_using_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [268]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [194]:
cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks


In [195]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
# from sklearn.datasets import load_iris

In [196]:
# from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [197]:
df = pd.read_csv('dataset2.csv')
# df = pd.read_excel("xxx.xls", sheet_name="sheet 1")
df.head()

Site  Payload Total (GB)  Traffic  Subs    Revenue Class Rev
0  Site 1               30419     1765  1414  134017424      Gold
1  Site 2               13872     1685   731   62952270    Silver
2  Site 3               28531     1070  1206  120884649      Gold
3  Site 4               10777      911   761   54450496    Bronze
4  Site 5               10990     1418   934   53238883    Bronze

In [198]:
#test_X = df.iloc[0:5,[2,3,4,5]].values
#print(test_X)

In [225]:
X = df.iloc[:,[1,2,3,4]].values
Y = df.iloc[:,[5]].values

In [ ]:
print (Y)

In [227]:
print (X)

[[    30419      1765      1414 134017424]
 [    13872      1685       731  62952270]
 [    28531      1070      1206 120884649]
 ...
 [    35575      3362      2371 196835590]
 [    12478      1608       901  65676942]
 [    45273      3988      3439 226109950]]


In [228]:
print(X.shape)
print(Y.shape)

(593, 4)
(593, 1)


In [229]:
target_names = df['Class Rev'].unique()
print(target_names)

['Gold' 'Silver' 'Bronze' 'Diamond' 'Platinum']


In [231]:
(trainX, testX, trainY, testY) = train_test_split(X, Y, random_state=3, test_size=0.4)
print(trainX.shape)
print(testX.shape)
print(trainY.shape)
print(testY.shape)

(355, 4)
(238, 4)
(355, 1)
(238, 1)


In [233]:
# define the dictionary of models our script can use, where the key
# to the dictionary is the name of the model (supplied via command
# line argument) and the value is the model itself
models = {
	"knn": KNeighborsClassifier(n_neighbors=3),
	"naive_bayes": GaussianNB(),
	"logit": LogisticRegression(solver="lbfgs", multi_class="auto"),
	"svm": SVC(kernel="rbf", gamma="auto"),
	"decision_tree": DecisionTreeClassifier(),
	"random_forest": RandomForestClassifier(n_estimators=100),
	"mlp": MLPClassifier()
}

In [234]:
# train the model
print("[INFO] using '{}' model".format("knn"))
model = models["knn"]
model.fit(trainX, trainY)

[INFO] using 'knn' model


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [235]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(predictions)

[INFO] evaluating...
['Silver' 'Silver' 'Gold' 'Gold' 'Gold' 'Gold' 'Silver' 'Bronze' 'Silver'
 'Silver' 'Silver' 'Gold' 'Silver' 'Gold' 'Gold' 'Silver' 'Gold' 'Gold'
 'Platinum' 'Bronze' 'Gold' 'Gold' 'Gold' 'Gold' 'Bronze' 'Bronze'
 'Silver' 'Gold' 'Silver' 'Silver' 'Gold' 'Gold' 'Silver' 'Gold' 'Gold'
 'Bronze' 'Gold' 'Gold' 'Platinum' 'Gold' 'Gold' 'Silver' 'Silver' 'Gold'
 'Silver' 'Bronze' 'Bronze' 'Gold' 'Gold' 'Bronze' 'Gold' 'Silver'
 'Bronze' 'Silver' 'Platinum' 'Gold' 'Gold' 'Gold' 'Gold' 'Silver'
 'Bronze' 'Gold' 'Gold' 'Bronze' 'Silver' 'Silver' 'Silver' 'Gold'
 'Bronze' 'Gold' 'Bronze' 'Bronze' 'Gold' 'Gold' 'Gold' 'Gold' 'Bronze'
 'Silver' 'Gold' 'Silver' 'Gold' 'Gold' 'Silver' 'Platinum' 'Platinum'
 'Gold' 'Bronze' 'Bronze' 'Gold' 'Bronze' 'Silver' 'Gold' 'Silver'
 'Silver' 'Gold' 'Gold' 'Silver' 'Gold' 'Gold' 'Gold' 'Silver' 'Gold'
 'Gold' 'Gold' 'Gold' 'Silver' 'Silver' 'Bronze' 'Bronze' 'Silver'
 'Bronze' 'Gold' 'Silver' 'Gold' 'Gold' 'Bronze' 'Gold' 'Silver' 'Gold'


In [238]:
print(classification_report(testY, predictions,
	target_names=target_names))

ValueError: ignored

In [239]:
# train the model
print("[INFO] using '{}' model".format("naive_bayes"))
model = models["naive_bayes"]
model.fit(trainX, trainY)

[INFO] using 'naive_bayes' model


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [240]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...
              precision    recall  f1-score   support

        Gold       0.95      0.98      0.96        41
      Silver       0.00      0.00      0.00         0
      Bronze       0.99      0.86      0.92       108
     Diamond       0.80      0.80      0.80        10
    Platinum       0.85      0.97      0.91        79

    accuracy                           0.92       238
   macro avg       0.72      0.72      0.72       238
weighted avg       0.93      0.92      0.92       238



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [244]:
# train the model
print("[INFO] using '{}' model".format("logit"))
model = models["logit"]
model.fit(trainX, trainY)

[INFO] using 'logit' model


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [245]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...


ValueError: ignored

In [246]:
# train the model
print("[INFO] using '{}' model".format("svm"))
model = models["svm"]
model.fit(trainX, trainY)

[INFO] using 'svm' model


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(gamma='auto')

In [247]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...


ValueError: ignored

In [248]:
# train the model
print("[INFO] using '{}' model".format("decision_tree"))
model = models["decision_tree"]
model.fit(trainX, trainY)

[INFO] using 'decision_tree' model


DecisionTreeClassifier()

In [249]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...


ValueError: ignored

In [250]:
# train the model
print("[INFO] using '{}' model".format("random_forest"))
model = models["random_forest"]
model.fit(trainX, trainY)

[INFO] using 'random_forest' model


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [251]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...


ValueError: ignored

In [252]:
# train the model
print("[INFO] using '{}' model".format("mlp"))
model = models["mlp"]
model.fit(trainX, trainY)

[INFO] using 'mlp' model


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier()

In [253]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = model.predict(testX)
print(classification_report(testY, predictions,
	target_names=target_names))

[INFO] evaluating...


ValueError: ignored

In [254]:
# import the necessary packages
from keras.models import Sequential
# from keras.layers.convolutional import Conv2D
# from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
# from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report
# from PIL import Image
# from imutils import paths
# import numpy as np
# import os

ImportError: ignored

In [ ]:
Y

In [256]:
# encode the labels, converting them from strings to integers
lb = LabelBinarizer()
labels = lb.fit_transform(Y)
print(labels)

NameError: ignored

In [257]:
(trainX, testX, trainY, testY) = train_test_split(X,	np.array(labels), test_size=0.4)
print(trainX.shape)
print(testX.shape)
print(trainY.shape)
print(testY.shape)

NameError: ignored

In [265]:
#model ANN

model = Sequential(
    [
        Dense(32, activation="relu", input_shape=(4,)), #hidden layer 1
        Dense(16, activation="relu"), #hidden layer 2
        # Dense(16, activation="relu"),
        # Dense(8, activation="sigmoid"),
        Dense(1, activation = "sigmoid"),
    ]
)

In [266]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 32)                160       
                                                                 
 dense_4 (Dense)             (None, 16)                528       
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 705
Trainable params: 705
Non-trainable params: 0
_________________________________________________________________


In [267]:
# train the model using the Adam optimizer
print("[INFO] training network...")
#opt = Adam(lr=1e-3, decay=1e-3 / 50)
model.compile(loss="binary_crossentropy", #optimizer=opt, #2 kelas --> binary_crossentropy
	metrics=["accuracy"])
H = model.fit(trainX, trainY, validation_data=(testX, testY), epochs=20, batch_size=20)

[INFO] training network...
Epoch 1/20


UnimplementedError: ignored

In [262]:
import matplotlib.pyplot as plt

print(H.history.keys())
# summarize history for accuracy
plt.plot(H.history['accuracy'])
plt.plot(H.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(H.history['loss'])
plt.plot(H.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

NameError: ignored